### ISSUE TITLE
Data Source Implementation Tracking

### ISSUE THREAD

**Issue by girotobial** [girotobial/bim_sort#21]
# Data Source Tracker
Supported data sources sourced from [microsoft documentation](https://learn.microsoft.com/en-us/azure/analysis-services/analysis-services-datasource#understanding-providers)

## Azure

- [ ] Azure SQL Database
- [ ] Azure Synapse Analytics (SQL DW)
- [ ] Azure Blob Storage
- [ ] Azure Table Storage
- [x] Azure CosmosDB
- [ ] Azure Data Lake Store Gen1
- [ ] Azure Data Lake Store Gen2
- [ ] Azure HDInsight HDFS
- [ ] Azure HDInsight Spark

## File

- [ ] Access Database
- [x] CSV File
- [ ] Excel Workbook
- [ ] Folder
- [ ] JSON Document
- [ ] Txt File
- [ ] XML table
- [ ] Lines from binary

## Database

- [x] PostgreSQL
- [ ] SQL Server
- [ ] SQL Server Data Warehouse
- [ ] Sybase Database
- [x] MySQL Database
- [ ] Analysis Services
- [ ] ODBC Query
- [ ] OLE DB
- [ ] Oracle

## Onine Services

- [ ] Analytic Platform System
- [ ] Dynamics 365
- [ ] Exchange
- [ ] OData Feed
- [ ] Sharepoint List

## SAP

- [ ] SAP Hana
- [ ] SAP Business Warehouse

## Salesforce

- [ ] Salesforce Objects
- [ ] Salesforce Reports
